mkdir -p triage/ramblr/x86/nopie
echo "Classify errors on triage/ramblr/x86/nopie"
grep '^E1FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E1FN.txt
grep '^E1FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E1FP.txt
grep '^E2FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E2FN.txt
grep '^E2FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E2FP.txt
grep '^E3FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E3FN.txt
grep '^E3FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E3FP.txt
grep '^E4FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E4FN.txt
grep '^E4FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E4FP.txt
grep '^E5FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E5FN.txt
grep '^E5FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E5FP.txt
grep '^E6FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E6FN.txt
grep '^E6FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E6FP.txt
grep '^E7FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E7FN.txt
grep '^E7FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E7FP.txt
grep '^E8FN' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E8FN.txt
grep '^E8FP' ./output/*/x86/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x86/nopie/E8FP.txt
mkdir -p triage/ramblr/x64/nopie
echo "Classify errors on triage/ramblr/x64/nopie"
grep '^E1FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E1FN.txt
grep '^E1FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E1FP.txt
grep '^E2FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E2FN.txt
grep '^E2FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E2FP.txt
grep '^E3FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E3FN.txt
grep '^E3FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E3FP.txt
grep '^E4FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E4FN.txt
grep '^E4FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E4FP.txt
grep '^E5FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E5FN.txt
grep '^E5FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E5FP.txt
grep '^E6FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E6FN.txt
grep '^E6FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E6FP.txt
grep '^E7FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E7FN.txt
grep '^E7FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E7FP.txt
grep '^E8FN' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E8FN.txt
grep '^E8FP' ./output/*/x64/*/nopie/*/*/errors/ramblr/sym_diff.txt > triage/ramblr/x64/nopie/E8FP.txt
mkdir -p triage/retrowrite/x64/pie
echo "Classify errors on triage/retrowrite/x64/pie"
grep '^E1FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E1FN.txt
grep '^E1FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E1FP.txt
grep '^E2FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E2FN.txt
grep '^E2FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E2FP.txt
grep '^E3FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E3FN.txt
grep '^E3FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E3FP.txt
grep '^E4FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E4FN.txt
grep '^E4FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E4FP.txt
grep '^E5FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E5FN.txt
grep '^E5FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E5FP.txt
grep '^E6FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E6FN.txt
grep '^E6FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E6FP.txt
grep '^E7FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E7FN.txt
grep '^E7FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E7FP.txt
grep '^E8FN' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E8FN.txt
grep '^E8FP' ./output/*/x64/*/pie/*/*/errors/retrowrite/sym_diff.txt > triage/retrowrite/x64/pie/E8FP.txt
mkdir -p triage/ddisasm/x86/pie
echo "Classify errors on triage/ddisasm/x86/pie"
grep '^E1FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E1FN.txt
grep '^E1FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E1FP.txt
grep '^E2FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E2FN.txt
grep '^E2FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E2FP.txt
grep '^E3FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E3FN.txt
grep '^E3FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E3FP.txt
grep '^E4FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E4FN.txt
grep '^E4FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E4FP.txt
grep '^E5FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E5FN.txt
grep '^E5FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E5FP.txt
grep '^E6FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E6FN.txt
grep '^E6FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E6FP.txt
grep '^E7FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E7FN.txt
grep '^E7FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E7FP.txt
grep '^E8FN' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E8FN.txt
grep '^E8FP' ./output/*/x86/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/pie/E8FP.txt
mkdir -p triage/ddisasm/x86/nopie
echo "Classify errors on triage/ddisasm/x86/nopie"
grep '^E1FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E1FN.txt
grep '^E1FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E1FP.txt
grep '^E2FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E2FN.txt
grep '^E2FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E2FP.txt
grep '^E3FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E3FN.txt
grep '^E3FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E3FP.txt
grep '^E4FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E4FN.txt
grep '^E4FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E4FP.txt
grep '^E5FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E5FN.txt
grep '^E5FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E5FP.txt
grep '^E6FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E6FN.txt
grep '^E6FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E6FP.txt
grep '^E7FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E7FN.txt
grep '^E7FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E7FP.txt
grep '^E8FN' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E8FN.txt
grep '^E8FP' ./output/*/x86/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x86/nopie/E8FP.txt
mkdir -p triage/ddisasm/x64/pie
echo "Classify errors on triage/ddisasm/x64/pie"
grep '^E1FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E1FN.txt
grep '^E1FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E1FP.txt
grep '^E2FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E2FN.txt
grep '^E2FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E2FP.txt
grep '^E3FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E3FN.txt
grep '^E3FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E3FP.txt
grep '^E4FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E4FN.txt
grep '^E4FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E4FP.txt
grep '^E5FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E5FN.txt
grep '^E5FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E5FP.txt
grep '^E6FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E6FN.txt
grep '^E6FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E6FP.txt
grep '^E7FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E7FN.txt
grep '^E7FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E7FP.txt
grep '^E8FN' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E8FN.txt
grep '^E8FP' ./output/*/x64/*/pie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/pie/E8FP.txt
mkdir -p triage/ddisasm/x64/nopie
echo "Classify errors on triage/ddisasm/x64/nopie"
grep '^E1FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E1FN.txt
grep '^E1FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E1FP.txt
grep '^E2FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E2FN.txt
grep '^E2FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E2FP.txt
grep '^E3FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E3FN.txt
grep '^E3FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E3FP.txt
grep '^E4FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E4FN.txt
grep '^E4FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E4FP.txt
grep '^E5FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E5FN.txt
grep '^E5FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E5FP.txt
grep '^E6FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E6FN.txt
grep '^E6FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E6FP.txt
grep '^E7FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E7FN.txt
grep '^E7FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E7FP.txt
grep '^E8FN' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E8FN.txt
grep '^E8FP' ./output/*/x64/*/nopie/*/*/errors/ddisasm/sym_diff.txt > triage/ddisasm/x64/nopie/E8FP.txt
